# Generated by Django 5.1.1 on 2024-10-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('coordinator', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_length', models.IntegerField()),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('exam_date', models.DateField()),
                ('enrollment_end_date', models.DateField()),
                ('exam_registration_end_date', models.DateField()),
                ('ug_pg', models.CharField(max_length=50)),
                ('core_elective', models.CharField(max_length=50)),
                ('course_type', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('join_link', models.URLField()),
                ('old_course_url', models.URLField(blank=True)),
                ('nptel_url', models.URLField(blank=True)),
                ('subjects', models.ManyToManyField(related_name='courses', to='course.subject')),
            ],
        ),
    ]
