# Generated by Django 5.1.1 on 2024-10-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='core_elective',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='course',
            name='enrollment_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='exam_registration_end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='join_link',
        ),
        migrations.RemoveField(
            model_name='course',
            name='old_course_url',
        ),
        migrations.AddField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
