# Generated by Django 5.1.1 on 2024-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_core_elective_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ug_pg',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_length',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
